version: "3.3"

services:
  model_tensorboard:
    container_name: model_tensorboard
    command: tensorboard --logdir /runs --bind_all
    build:
      context: .
      dockerfile: ./Tensorboard.Dockerfile
    network_mode: host
    environment:
      CONTAINER: tensorboard
    volumes:
      - training_runs:/runs
  model_training:
    container_name: model_training
    command: python -m modeling.train_model
    build:
      context: .
      dockerfile: ./Training.Dockerfile
    network_mode: host
    environment:
      CONTAINER: training
#      CUDA_LAUNCH_BLOCKING: 1
    volumes:
      - training_runs:/runs
    deploy:
      resources:
        reservations:
          devices:
            -   driver: nvidia
                count: 1
                capabilities: [ gpu ]

volumes:
  training_runs: